jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 21
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        BUILD_RELEASE: ${{ github.event.prerelease == false }}
      name: Upload assets to CurseForge
      run: ./gradlew build
    - continue-on-error: true
      name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: build/libs/*.jar;!build/libs/*-dev.jar;LICENSE
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: release-artifacts
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
